### ISSUE TITLE
Run SamBamba + FreeBayes on an PODK node against the 234G version of NA12878

### ISSUE THREAD

**Issue by hannes-ucsc** [BD2KGenomics/adam-contest-eval#4]

**Comment by hannes-ucsc** [comment]
Beau knows where to find that BAM

**Comment by almussel** [comment]
We are running these as a benchmark to compare to ADAM, yes? Which of the programs in sambamba are the ones we're concerned with, and what data on those runs do we care about?

**Comment by beaunorgeot** [comment]
The goal is an end-to-end germline pipeline; taking a bam as input and
outputting qualified variants. Important data points are time (for each
step in the pipeline) and variant concordance (w/in acceptable standards).
Does this make sense? I can chat this afternoon if you'd like

**Comment by fnothaft** [comment]
@mbaudrey you'd want sort and markdups from sambamba. You should be able to run these through a pipe with freebayes.

**Comment by hannes-ucsc** [comment]
Status in progress, currently installed tools on m3.xlarge instance. Will need to restart as r3.???.

**Comment by almussel** [comment]
What is the most appropriate reference genome to use for this? Freebayes needs one.

**Comment by beaunorgeot** [comment]
You need your reference genome to match your sample. Are you able to
determine which reference your sample was aligned/mapped to? If so, that's
the reference you want. Let me know if you need help determining the
alignment sequence
